# -*- mode: ruby -*-
# vi: set ft=ruby :

#Script zum apache2 basic auth automatisieren

Vagrant.configure("2") do |config|

  # Fileserver
  config.vm.define "ubuntuserver01" do |webserver|
    webserver.vm.hostname = "LL-Webserver"
    webserver.vm.box = "ubuntu/xenial64"
    webserver.vm.synced_folder ".", "/var/www/html"
    
    # Network Configs
    webserver.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
    webserver.ssh.forward_agent = true

    # VM Configs
    webserver.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "Webeserver"

      # VM Specs
      vb.memory = "2048"
      vb.cpus = "2"
    end
end